# fly.toml app configuration file generated for server-polished-haze-1918 on 2025-11-12T22:39:49+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-polished-haze-1918'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
